name: FragileLife
version: '1.0-SNAPSHOT'
main: com.birdy.fragileLife.FragileLife
api-version: '1.21'
commands:
  chat:
    description: Change your chat color!
    aliases:
      - c
  gift:
    description: Gift another player a heart (8h Cooldown)
  greetings:
    description: Change your join message
  missions:
    description: View the missions GUI
  tags:
    description: View the TAGS GUI
  reaction:
    description: View Reaction Stats
  nick:
    description: Change your nickname
    aliases:
      - nickname
  store:
    description: Open the store
    aliases:
      - s
  soulfragment:
    description: Admin command to adjust player soul fragments
    aliases:
      - sf
    usage: sf <get|add|remove|set> <name> <amount>
  slot:
    description: Gamble away your life savings
    aliases:
      - gamble